# Generated by Django 3.0.6 on 2020-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200603_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
    ]
